### ISSUE TITLE
Vertical Button Group not aligned

### ISSUE THREAD

**Issue by KaRkY** [DesignRevision/shards-react#1]
In Chrome 71 on windows 10 vertical button group is not alligned properly.

https://imgur.com/zARumAt

**Comment by hisk** [comment]
@KaRkY Thank you for submitting this! 😄I will review it and provide a fix as soon as possible.

**Comment by hisk** [comment]
✅Fixed in Shards 2.1.1 / Shards React 1.0.2 - https://github.com/DesignRevision/shards-react/commit/0c7185d777bc5e04c50b233e699908bf9f3710bd
