### ISSUE TITLE
Defining default theme in Shards?

### ISSUE THREAD

**Issue by stickyburn** [DesignRevision/shards-react#13]
Hi guys! Thanks for the awesome project!
I was wondering how to change my default theme's primary and secondary colours. Do I just define a theme object and render it with my main App component? 

Thanks!

**Comment by Calfredop** [comment]
Hello,
Yes I would also like a quick guide to global theming or some reference to look into.
Thanks

**Comment by magrinj** [comment]
Any help here ? Is it possible to did it without building from scratch shards-ui ?

**Comment by ogaston** [comment]
Any of you could solve it?

**Comment by aueangpanit** [comment]
Currently using this method until there's an official doc

index.css
`[class*='primary'] {
  background-color: red;
  border-color: red;
}`

Should work for other theme colors too: 
Primary #0067F4
Secondary #5A6169
Success #17C671
Info #00B8D8
Warning #FFB400
Danger #C4183C
Light #E9ECEF
Dark #212529

**Comment by stickyburn** [comment]
Just going to close this :skull:
