### ISSUE TITLE
Whats the difference

### ISSUE THREAD

**Issue by The-Code-Monkey** [DesignRevision/shards-react#2]
What is the real point of this due to already established things like reactstrap which this is pretty much just a clone of?? or just writing the bootstrap yourself??

**Comment by hisk** [comment]
@The-Code-Monkey Please see my related answer [here](https://github.com/DesignRevision/shards-vue/issues/14#issuecomment-456929064). 🙂

**Comment by The-Code-Monkey** [comment]
Fair enough point.
