### ISSUE TITLE
How to grab values from forms?

### ISSUE THREAD

**Issue by ivelichkovich** [DesignRevision/shards-react#4]
I followed this documentation to create a form: https://designrevision.com/docs/shards-react/component/form.

A form isn't very useful if you can't access the user supplied values so I'm trying to figure out how to access the values entered into the form.

I have a button in my form that when clicked I want to call a method and from that method access the form values. How do you do this?

I'm also new to react should I could be missing something obvious but help would be greatly appreciated.

**Comment by frechette-alex** [comment]
https://reactjs.org/docs/forms.html
