### ISSUE TITLE
README link to documentation is broken.

### ISSUE THREAD

**Issue by CarnesT** [DesignRevision/shards-react#8]
Greetings!

I believe the link to your documentation can be found here: https://designrevision.com/docs/shards-react/getting-started

If I click the "Documentation & Demo" link, it redirects to the correct URL. However, results in the following error:
![image](https://user-images.githubusercontent.com/22307146/58298571-e018e000-7d90-11e9-8e7e-c8ba83bf1e92.png)

Hopefully this helps (if you were not aware of the issue)!

**Comment by cookieshell** [comment]
I couldn't replicate this. Please clear your browser's cache and try again or try using incognito mode.
